


//swagger file 
const swaggerAutogen=require('swagger-autogen')();


//import swagger definitions from data/swaggerdefinitions.js
const swaggerDefinitions=require('./data/swaggerdefinitions.js');

const doc= {
    info: {
        version:"1.0.0",
        title:"Noroff E-Commerce ",
        description:"Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host:"localhost:3000",

    tags: [
        {
            name:"Brand",
            description:"Brand operations"
        },
        {
            name:"Category",
            description:"Category operations"
        },
        {
            name:"Product",
            description:"Product operations"
        },
        {
            name:"Order",
            description:"Order operations"
        },
        {
            name:"User",
            description:"User operations"
        },
        {
            name:"Admin",
            description:"Admin operations. The routes inside this group render pages for admin. It is seperate unit than Backend.Use Backend Routes for json responses "
        }

        
    ],



    definitions: {
        ...swaggerDefinitions //importing swagger definitions
        
    },
    components: {
        securitySchemes: {
            bearerAuth: {
                type:"http",
                in:"header",
                description:"JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
                scheme:"bearer",
                bearerFormat:"JWT"
            },
        },
    },
    security: [
        {
            bearerAuth: []
        }
    ]

};

const outputFile='./swagger_output.json';
const endpointsFiles=['./app.js','./controllers/BrandController.js',

];


swaggerAutogen(outputFile,endpointsFiles,doc).then(()=> {
    require('./bin/www');
});
